version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    restart: always
    environment:
      NGINX_PORT: 8080
